
openapi: 3.0.1
info:
  title: The Odds API
  description: Retrieve sports betting odds from sportsbooks across various markets.
  version: 1.0.0
servers:
  - url: https://api.the-odds-api.com/v4
paths:
  /sports:
    get:
      summary: Get all active sports
      parameters:
        - in: query
          name: apiKey
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of sports
  /sports/{sport}/odds:
    get:
      summary: Get odds for a specific sport
      parameters:
        - in: path
          name: sport
          required: true
          schema:
            type: string
        - in: query
          name: regions
          required: true
          schema:
            type: string
        - in: query
          name: markets
          required: true
          schema:
            type: string
        - in: query
          name: apiKey
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Betting odds
